// <auto-generated />
namespace Repositorio.Dao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VERSAO_DB_133_ADD_TABLE_USUARIO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VERSAO_DB_133_ADD_TABLE_USUARIO));
        
        string IMigrationMetadata.Id
        {
            get { return "201712271659257_VERSAO_DB_1.3.3_ADD_TABLE_USUARIO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
