// <auto-generated />
namespace Repositorio.Dao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VERSAO_DB_102 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VERSAO_DB_102));
        
        string IMigrationMetadata.Id
        {
            get { return "201712261231523_VERSAO_DB_1.0.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
