// <auto-generated />
namespace Repositorio.Dao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VERSAO_BD_111_ADD_TBL_CIDADE_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VERSAO_BD_111_ADD_TBL_CIDADE_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201712261258239_VERSAO_BD_1.1.1_ADD_TBL_CIDADE_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
