// <auto-generated />
namespace Repositorio.Dao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VERSAO_DB_122_MODIFICACAODECAMPOSNULOS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VERSAO_DB_122_MODIFICACAODECAMPOSNULOS));
        
        string IMigrationMetadata.Id
        {
            get { return "201712261908399_VERSAO_DB_1.2.2_MODIFICACAO DE CAMPOS NULOS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
